name: qwen3-tts
services:
  qwen3-tts:
    container_name: qwen3-tts-truenas

    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: all
              driver: nvidia

    image: pytorch/pytorch:2.10.0-cuda12.8-cudnn9-devel

    ports:
      - "8000:8000"

    volumes:
      - "/mnt/MEGA-Storage/Docker-tests/qwen3-tts/data:/data"

    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=Etc/UTC
      - HF_HOME=/data/hf
      - HF_HUB_CACHE=/data/hf
      - ATTENTION_IMPL=flash_attention_2
      - CUDA_HOME=/usr/local/cuda

    entrypoint: ["/bin/bash", "-lc"]

    command:
      - "set -euo pipefail;

        apt-get update;
        # apt-get install -y --no-install-recommends ffmpeg libsndfile1 sox git python3-venv;
        rm -rf /var/lib/apt/lists/*;

        export CUDA_HOME=/usr/local/cuda;
        export PATH=$CUDA_HOME/bin:$PATH;
        /usr/local/cuda/bin/nvcc --version;

        python3 -m venv /opt/venv;

        /opt/venv/bin/python -m pip install -U pip setuptools wheel packaging;
        /opt/venv/bin/python -m pip install -U qwen-tts gradio;

        TORCH_CUDA_ARCH_LIST=8.6 MAX_JOBS=1 CUDA_HOME=/usr/local/cuda /opt/venv/bin/python -m pip install -U flash-attn --no-build-isolation -v;

        /opt/venv/bin/python -c \"import torch; print('torch:', torch.__version__); print('cuda:', torch.cuda.is_available()); print('torch cuda:', torch.version.cuda); import flash_attn; print('flash_attn: import ok')\";

        /opt/venv/bin/python /data/app.py"
